service: data-island-api
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x

plugins:
  - serverless-plugin-typescript
  - serverless-dynamodb-local
  - serverless-offline

functions:
  getPortfolios:
    handler: src/functions/portfolio/get-portfolios.handler
    events:
      - httpApi:
          path: /portfolios
          method: get
  createPortfolio:
    handler: src/functions/portfolio/post-portfolio.handler
    events:
      - httpApi:
          path: /portfolios
          method: post
  deletePortfolio:
    handler: src/functions/portfolio/delete-portfolio.handler
    events:
      - httpApi:
          path: /portfolios/{portfolioId}
          method: delete
  updatePortfolio:
    handler: src/functions/portfolio/put-portfolio.handler
    events:
      - httpApi:
          path: /portfolios/{portfolioId}
          method: put

resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: disl_portfolio
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

custom:
  dynamodb:
    stages:
      - dev
    start:
      docker: true
      port: 8000
      inMemory: true
      migrate: true
      seed: true
      convertEmptyValues: true
