name: deploy-production
on: 
  workflow_dispatch:
jobs:
  web-deploy:
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest
    environment: 
      name: production
      url: https://.dataisland.io
    steps:
      - name: Download build artifacts
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.TOKEN_GITHUB_ARTIFACT_READ}}
          workflow: main.yml
          name: data-island-web-dist
          path: data-island-web-dist
          workflow_conclusion: success

      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --delete
        env:
          AWS_S3_BUCKET: dataisland.io
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: data-island-web-dist

      - name: Invalidate Cloudfront cache
        uses: chetan/invalidate-cloudfront-action@v2
        env:
          DISTRIBUTION: ${{ secrets.DISTRIBUTION }}
          PATHS: "/*"
          AWS_REGION: "us-east-1"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}