name: deploy-staging
on:
  push:
    branches:
      - '**'
      - '!master'
jobs:
  web-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./data-island-web
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build:prod -- --base-href=$/{{ github.ref_name }}/

      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --delete
        env:
          AWS_S3_BUCKET: staging.dataisland.io
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: data-island-web/dist/data-island-web/
          DEST_DIR: "{{ github.ref_name }}"

      - name: Logging
        run: echo "{{ github.ref_name }}"