name: main
on:
  push:
    branches: ["main"]
  workflow_dispatch:
jobs:
  web:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./data-island-web
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Test
        run: npm run test

      - name: Build application
        run: npm run build:prod

      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: "./data-island-web/dist/data-island-web"
